# sample config used to demonstrate ssh tunneling
version: 2
jobs:
   build:
     docker:
      - image: docker:17.10.0-ce-git
     steps:
      - checkout

      # - setup_remote_docker

      # - run: chmod +x .circleci/sample_script.sh && .circleci/sample_script.sh
      - run: curl -vvv -s -X PUT -d "`cat aglet_v.yaml`" -H "X-Aglet-Token: \"${AGLETPREPRODTOKEN}\"" -k "http://httpbin.org/put"