version: 2.1
executors:
  no-cache:
    machine: true
  with-cache:
    machine:
      docker_layer_caching: true

jobs:
  build:
    parameters:
      e: # e for executor
        type: executor
    executor: << parameters.e >>
    steps:
      - run: echo outside the executor

workflows:
  arbitrary-workflow-name:
    jobs:
      - build:
          e: no-cache
      - build:
          e: with-cache