version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run: echo $CIRCLE_STAGE
  test:
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run: $CIRCLE_STAGE
  test-acceptance:
    docker:
      - image: circleci/golang:1.8
    steps:
      - run: $CIRCLE_STAGE
  deploy-prod:
    docker:
      - image: circleci/golang:1.8
    steps:
      - run: $CIRCLE_STAGE

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - test-acceptance:
          requires:
            - build
      - deploy-prod:
          type: approval
          requires:
            - test
            - test-acceptance