version: 2

jobs:
    build:
        docker:
            - image: circleci/python:latest
        steps:
            - checkout
            - run:
                name: "hello world"
                command: echo "hello world"
            - run:
                name: "hello python"
                command: python -c "print('hello python')"
