# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#

version: 2
jobs:
  build:
    machine: true
    parallelism: 4
    environment:
      - TESTFILES: $whoami
    parallelism: 4
    steps:
      - checkout

      - run:
          name: test
          command:
            echo ${TESTFILES}


      # run tests!
      #- run: 
      #    name: Run tests
      #    command: |
      #      mvn -f rest/pom.xml -P common,stand-alone -Dtest=${TESTFILES} -e test

