version: 2
jobs:
  build:
    docker:
      - image: circleci/python:latest
    # working_directory: /
    steps:
      - checkout
      - run:
          name: basic
          command: |
            echo "CRON jobs are cool"