# sample config used to demonstrate ssh tunneling
version: 2
jobs:
   build:
     machine: true
       # - image: circleci/golang:1.8
     steps:
       #- checkout
       # - run: echo "hello world" > sayHi.txt
       # - run: pwd

       - run: sdk install gradle 4.6
