version: 2
jobs:
  build:
    working_directory: ~/{GH-REPO}
    #environment:
    #  IMAGE_TAG: ${CIRCLE_SHA1}

    docker:
       - image: circleci/golang:1.9

    steps:
      - checkout

      # - setup_remote_docker:
      #    reusable: true
      
      - run: docker
      
      #push docker iamge to docker hub
      # - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      # - run: docker push $DOCKER_USER/{GH-REPO}-uwsgi:${CIRCLE_SHA1}