version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run: sleep 180
  test:
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run: sleep 180
  anotherTest:
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run: sleep 180

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: org-global
      - test
      - anotherTest

