version: 2
jobs:
  build:
    docker:
      - image: golang:1.8
    working_directory: /go/src/github.com/CircleCI-Public/circleci-demo-docker
    steps:
      - checkout
      # ... steps for building/testing app ...

      #- setup_remote_docker:   # (2)
      #    docker_layer_caching: true # (3)

      # use a primary image that already has Docker (recommended)
      # or install it during a build like we do here
      - run:
          name: system stats
          command: |
            echo "Ave Mundus!"