version: 2
jobs:
  one:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: sleep 25
  two:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A more familiar hi"
      - run: sleep 15
  three:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run: echo "Hello from container 3!"
      - run: sleep 360


workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
      - three