version: 2
jobs:
   build:
     docker:
       - image: circleci/openjdk:8-jdk
     steps:
       - checkout
       - run: echo "hello world"
       - run:
          name: Install AWSCLI
          command: |
            sudo apt-get -y -qq update
            # sudo apt-get -y -qq install python3.4-dev
            # wget https://bootstrap.pypa.io/get-pip.py
            # python3.4 get-pip.py --user
            # pip install awscli --upgrade --user
            # export PATH=$PATH:$HOME/local/bin

