version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201711-01
    # working_directory: ~/{GH-REPO}
    #environment:
    #  IMAGE_TAG: ${CIRCLE_SHA1}

    steps:
      - checkout
      - run:
          name: Build Box
          command: echo $DOCKER_PASSWD | docker login $DOCKER_REGISTRY -u $DOCKER_USER --password-stdin

      # - setup_remote_docker
        # reusable: true
      
      #- run: docker build -t chris/test:${CIRCLE_SHA1} .
      # - run: docker images
      
      #push docker iamge to docker hub
      # - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      # - run: docker push $DOCKER_USER/{GH-REPO}-uwsgi:${CIRCLE_SHA1}
