version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2
    steps:
      # - checkout
      - run:
          name: HAHA
          command: |
            TEST=123
            echo $TEST
            export TEST
            echo "export TEST=123" >> $BASH_ENV
      - run:
          name: Voila
          command: |
            echo $TEST