version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run: echo "Hello, from build!"
  test:
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run: echo "Hello, from test!"
  test-acceptance:
    docker:
      - image: circleci/golang:1.8
    steps:

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
      - test-acceptance