version: 2.1
orbs:
  slack: circleci/slack@2.0.0
jobs:
  build:
    parallelism: 3
    docker:
      - image: circleci/ruby:2.4.2-jessie-browsers
    steps:
      - checkout
      - run: echo "Hello, world"
  
  test:
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run: echo $CIRCLE_STAGE
  
  deploy-staging:
    docker:
      - image: circleci/golang:1.8
    steps:
      - run: echo $CIRCLE_STAGE
      - slack/status:
          mentions: 'chris'
          webhook: ${SLACK_WEBHOOK}


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy-staging:
          requires:
            - test
      #- deploy-prod:
      #    type: approval
      #    filters:
      #      branches:
      #        only: master
      #    requires:
      #      - deploy-staging