# sample config used to demonstrate ssh tunneling
version: 2
jobs:
   build:
     machine: true
     steps:
      - checkout
      - run: chmod +x .circleci/sample_script.sh && .circleci/sample_script.sh