version: 2.1
jobs:
  build:
    parallelism: 3
    docker:
      - image: centos/postgresql-10-centos7
    steps:
      - checkout
      - run: echo $CIRCLE_USERNAME


workflows:
  version: 2
  build_and_test:
    jobs:
      - build