version: 2
jobs:
  build-and-test:
    macos:
      xcode: "9.1"

    parallelism: 2
    steps:
      - checkout
      - run:
          name: Fetch CocoaPods Specs
          command: |
            echo Hello from $CIRCLE_NODE_INDEX

workflows:
  version: 2
  build-test-lint:
    jobs:
      # - swiftlint
      # - danger
      - build-and-test