# sample config used to demonstrate ssh tunneling
version: 2
jobs:
   build:
     machine: true
     steps:

       - run:
           command: sudo apt-get update

       - run:
           command: sudo apt-get install openvpn

       - run:
           command: openvpn --version

