build:
  branches:
    only:
      - circle-docker-abomination

workflows:
  version: 2
  my_workflow:
    jobs:
      - download_code
  # - download_code:
  #    requires: download_code

jobs:
  download_code:
    # executor: dind
    docker: 
      - image: dind
    steps:
      - setup_remote_docker
      - run:
          name: Download source code from GitHub
          command: |
            # curl -L -u xxx:xxx \
            #   https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tarball/$CIRCLE_SHA1 > source.tar.gz
            # tar --strip-components=1 -xzf source.tar.gz && rm source.tar.gz
      - run:
          name: "Build Docker image: src-$CIRCLE_SHA1"
          command: |
            # docker info
            # docker login -u AWS -p xxx https://451899138981.dkr.ecr.us-east-1.amazonaws.com
            # docker build -t src-$CIRCLE_SHA1 -f .circleci/jobs/download_code .

# executors:
#   dind:
#    docker:
#      - image: dind