version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: ~/aedifex/
    environment:
      BASH_ENV: 'env_file'
    steps:
      - checkout
      - run:
          name: Run Test Suite
          command: |
            ls
            pwd
      - store_artifacts:
          path: /home/circleci/aedifex/tests.html
