# sample config used to demonstrate ssh tunneling
version: 2
jobs:
   build:
     machine: true
       # - image: circleci/golang:1.8
     steps:
       #- checkout
       # - run: echo "hello world" > sayHi.txt
       # - run: pwd

       # - run: wget https://services.gradle.org/distributions/gradle-4.6-bin.zip?_ga=2.7228658.1354325567.1520625056-1682346861.1520625056
       # - run: ./gradle
       - run: docker pull circleci/android:api-26-alpha
       - run: docker exec -it circleci/android:api-26-alpha ./gradlew
