# store artifacts and post a link

version: 2
jobs:
  build:
    machine: true
    environment:
      - ARTIFACT_URL: ""

    working_directory: /tmp
    steps:
      - run:
          name: create, store, and upload build artifacts
          command: |
            echo "Hello, I am a build artifact!" > /tmp/artifact-1

      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file

      #- store_artifacts:
      #    path: /tmp/artifacts

      - run:
          name: get artifact url
          command: |
            curl https://circleci.com/api/v1.1/project/github/CharlesBlack89/circleci_sandbox/$CIRCLE_BUILD_NUM/artifacts?circle-token=$CIRCLE_TOKEN -v | grep -o 'https://[^"]*' > artifactURLs.txt
            cat artifactURLs.txt


      - run:
          name: send artifact link via Slack
          command: |
            # $(awk 'NR==1{print $1; exit}' artifacts.txt) > ARTIFACT_URL
            # curl -X POST -H 'Content-type: application/json' --data '{"text":"<'"${ARTIFACT_URL}"'|Click here> to see the test results of your last build!"}' https://hooks.slack.com/services/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

