version: 2
jobs:
  build:
    #docker:
    #  - image: circleci/golang:1.8
    machine: true
    steps:
      - checkout
      - run: echo $AWS_CREDS  
      # - run: sudo whoami
  test:
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run: echo $AWS_CREDS

workflows:
  version: 2
  build_and_test:
    # triggers sub WF nomen
    #triggers:
    #  - schedule:
    #      cron: "* * * * *"
    #      filters:
    #        branches:
    #          only:
    #            - master
    jobs:
      - build:
          context: org-global
          type: approval
      #- test:
      #    context: org-global

