version: 2.1

orbs:
  slack: circleci/slack@2.0.0

workflows:
  build_deploy:
    jobs:
      - build

jobs:
  build:
    machine: true
    resource_class: aedifex/runner-test
    working_directory: ~/app
    steps:
      - checkout
      - run:
          command: |
            echo "Hello, from from $hostname!"
