version: 2
jobs:
  build:
    working_directory: ~/{GH-REPO}
    #environment:
    #  IMAGE_TAG: ${CIRCLE_SHA1}

    docker:
       - image: circleci/ruby:2.4-node

    steps:
      - checkout

      - setup_remote_docker
        # reusable: true
      
      - run: docker build -t chris/test:${CIRCLE_SHA1} .
      - run: docker images
      
      #push docker iamge to docker hub
      # - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      # - run: docker push $DOCKER_USER/{GH-REPO}-uwsgi:${CIRCLE_SHA1}
