# sample config used to demonstrate ssh tunneling
version: 2
jobs:
   build:
     machine: true
     steps:
       # - run: curl -vvv -s -X PUT -d "`cat aglet_v.yaml`" -H "X-Aglet-Token: \"${AGLETPREPRODTOKEN}\"" -k "http://httpbin.org/put"
       - run: curl -vvv -s -X PUT -d "``" -k "http://httpbin.org/put"