version: 2
jobs:
   build:
     docker:
       - image: circleci/openjdk:8-jdk
     steps:
       - checkout
       - run: echo "hello world"
       - run:
          name: Install AWSCLI
          command: |
            sudo apt-get update && sudo apt-get install -qq -y python-pip libpython-dev
            curl -O https://bootstrap.pypa.io/get-pip.py && sudo python get-pip.py
            sudo pip install -q awscli --upgrade
            aws --version
