version: 2
jobs:
  build:
    # parallelism: 4
    # machine: true
    docker:
      - image: circleci/python:latest
    # working_directory: /
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: split
          # when: always
          command: |
            echo "HI!"
