version: 2
jobs:
  build:
    docker:
      - image: python:3.6.0
    environment:
      - ARTIFACT_URL: ""

    working_directory: /tmp
    steps:
      - run:
          name: Hacking together custom webhook
          command: |
            # echo "my artifact file" > /tmp/artifact-1;
            # mkdir /tmp/artifacts;
            # echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;
            curl https://circleci.com/api/v1.1/project/github/CharlesBlack89/circleci_sandbox/106/artifacts?circle-token=$CIRCLE_TOKEN -v | grep -o 'https://[^"]*' > artifacts.txt
            $(awk 'NR==1{print $1; exit}' artifacts.txt) > ARTIFACT_URL
            curl -X POST -H 'Content-type: application/json' --data '{"text":"<'"${ARTIFACT_URL}"'|Click here> to see the test results of your last build!"}' https://hooks.slack.com/services/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

      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file

      - store_artifacts:
          path: /tmp/artifacts