version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run: echo $CIRCLE_STAGE
  test:
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run: $CIRCLE_STAGE

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build