version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run: echo $CIRCLE_JOB
  test:
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run: $CIRCLE_JOB

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          environment:
            NAME: chris
      - test:
          requires:
            - build