version: 2
jobs:
  build:
    docker:
      - image: python:3.6.0

    working_directory: /tmp
    steps:
      - run:
          name: Hacking together custom webhook
          command: |
            # echo "my artifact file" > /tmp/artifact-1;
            # mkdir /tmp/artifacts;
            # echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;
            curl -X POST -H 'Content-type: application/json' --data '{"text":"<'"${CIRCLE_BUILD_URL}"'|Click here> for details!"}' https://hooks.slack.com/services/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

      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file

      - store_artifacts:
          path: /tmp/artifacts