version: 2
jobs:
  build-and-test:
    macos:
      xcode: "9.0"

    steps:
      - checkout
      - run:
          name: Fetch CocoaPods Specs
          command: |
            echo hello!

workflows:
  version: 2
  build-test-lint:
    jobs:
      # - swiftlint
      # - danger
      - build-and-test