version: 2
jobs:
   build:
     docker:
      # get image with AWS CLI or....
       - image: circleci/python:latest
     steps:
       - checkout

       - run: exit 0

      # get aws cli
       - run:
          name: Install AWSCLI
          command: |
            sudo apt-get -y -qq update
            sudo apt-get -y -qq install python3.4-dev
            wget https://bootstrap.pypa.io/get-pip.py
            python3.4 get-pip.py --user
            pip install awscli --upgrade --user
            export PATH=$PATH:$HOME/local/bin
            aws cli

