# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#

version: 2
jobs:
  build:
    machine: true
    environment:
      - FOO: "bar"
    parallelism: 4
    steps:
      - checkout
    



      - run:
          name: Split tests
          command: |
            TESTFILES=$(whoami)

      # run tests!
      - run:
          name: Run tests
          command: |
            echo ${TESTFILES}
            echo ${FOO}

