version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      # - run: kubectl run hello-web --image=gcr.io/${PROJECT_ID}/hello-app:v1 --port 8080
      # - run: sleep 25
      - run: kubectl get pods
  test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A more familiar hi"
      # - run: sleep 15
      - run: exit 0


workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      #- test:
      #    requires:
      #      - build