version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout
      - run: echo "1"
  m1:
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout
      - run: echo "1"

  m2:
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout
      - run: echo "1"

  m3:
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout
      - run: echo "1"

  deploy:
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout
      - run: echo "1"

experimental:
  notify:
    branches:
      only:
        - master

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - m1
      - m2
      - m3