# sample config used to demonstrate ssh tunneling
version: 2
jobs:
   build:
     docker:
       - image: circleci/golang:1.8
     steps:
       - checkout
       # - run: echo "hello world" > sayHi.txt
       # - run: pwd

       - add_ssh_keys:
          fingerprints:
            - f7:1f:3b:84:fa:6f:30:75:93:6b:ff:ce:59:a5:ba:1b

