# sample config used to demonstrate ssh tunneling
version: 2
jobs:
   build:
     machine: true
       # - image: circleci/golang:1.8
     environment:
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m"'
     steps:
       - checkout

       - run: docker pull circleci/android:api-26-alpha
       # - run: echo "hello world" > sayHi.txt
       # - run: pwd

       
