workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: tmm

version: 2
jobs:
   build:
     docker:
       - image: circleci/ruby:latest
     working_directory: ~/app
     steps:
       - checkout
       - run: echo "Hello, Context"