version: 2
jobs:
  build:
    docker:
      - image: circleci/python:latest
    # working_directory: /
    steps:
      # - setup_remote_docker
      - checkout
      - run:
          name: basic
          when: always
          command: |
            notAcommand
      - run:
          name: semper
          when: always
          command: |
            echo $?