# sample config used to demonstrate ssh tunneling
version: 2
jobs:
   build:
     docker:
      - image: circleci/golang:1.8
     steps:
      - checkout

      - setup_remote_docker

      - run: chmod +x .circleci/sample_script.sh && .circleci/sample_script.sh