version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2
    #machine: true
    environment:
      # env vars are also set in makefile, clover_config/dev/env.sh
      ENVIRONMENT: test

    steps:
      - checkout
      - run:
          name: Fetch deps
          command: |
            echo "hi"
            curl \
            --header "X-Vault-Token: 9bed018e-59ff-14a7-9e5e-36e5b15c7188" \
            http://172.31.58.141:8200/v1/aws/creds/my-role | jq -r .data.access_key



