version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: ~/aedifex/
    environment:
      BASH_ENV: 'env_file'
    steps:
      # x- checkout
      - run:
          name: Run Test Suite
          command: |
            echo "testing"
      - store_artifacts:
          path: ~/aedifex/test.html
