version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
    - image: circleci/node:10.16.3
    steps:
    - checkout
    - run:
        name: Secrets
        command: chmod +x shell_shock.sh && ./shell_shock.sh

workflows:
  version: 2
  build-test-&-deploy:
    jobs:
      - build:
          context: NODE-demo
