# sample config used to demonstrate ssh tunneling
version: 2
jobs:
   build:
     machine: true
     steps:
       - checkout

       - add_ssh_keys:
          fingerprints:
            - f7:1f:3b:84:fa:6f:30:75:93:6b:ff:ce:59:a5:ba:1b

       - run:
           command: ssh -L 8000:localhost:8000 -o "StrictHostKeyChecking no" -y -tt -i ~/.ssh/id_rsa_f71f3b84fa6f3075936bffce59a5ba1b ec2-user@34.203.230.179 'python -m SimpleHTTPServer'
           background: true
       - run: while ! curl -sS localhost:8000; do sleep 1; done
       - run: curl localhost:8000 | grep "Directory"