version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run:
          name: Run Test Suite
          command: |
            echo "Run additional tests?" $RUN_EXTRA_TESTS
